/**
 * @author SATO Kentaro
 * @license BSD-2-Clause
 */

enum {
	CBOR_TAG_SELF_DESCRIBE = 55799,

	CBOR_TAG_STRING_REF_NS = 256,
	CBOR_TAG_STRING_REF = 25,

	CBOR_TAG_SHAREABLE = 28,
	CBOR_TAG_SHARED_REF = 29,

	CBOR_TAG_DATETIME = 0,
	CBOR_TAG_EPOCH = 1,
	CBOR_TAG_BIGNUM_U = 2,
	CBOR_TAG_BIGNUM_N = 3,
	CBOR_TAG_DECIMAL = 4,
	CBOR_TAG_BIGFLOAT = 5,
	CBOR_TAG_TO_BASE64URL = 21,
	CBOR_TAG_TO_BASE64 = 22,
	CBOR_TAG_TO_HEX = 23,
	CBOR_TAG_CBOR_DATA = 24,
	CBOR_TAG_URI = 32,
	CBOR_TAG_BASE64URL = 33,
	CBOR_TAG_BASE64 = 34,
	CBOR_TAG_PCRE_REGEX = 35,
	CBOR_TAG_MIME_MSG = 36,
};
