/**
 * @author SATO Kentaro
 * @license BSD-2-Clause
 */

enum {
	CBOR_TAG_SELF_DESCRIBE = 55799,

	CBOR_TAG_STRING_REF_NS = 256,
	CBOR_TAG_STRING_REF = 25,

	CBOR_TAG_SHAREABLE = 28,
	CBOR_TAG_SHARED_REF = 29,

	CBOR_TAG_DATETIME = 0,
	CBOR_TAG_BIGNUM_U = 2,
	CBOR_TAG_BIGNUM_N = 3,
	CBOR_TAG_DECIMAL = 4,
};
