/**
 * @author SATO Kentaro
 * @license BSD-2-Clause
 */

enum {
	PHP_CBOR_TAG_SELF_DESCRIBE = 55799,
	
	PHP_CBOR_TAG_STRING_REF_NAMESPACE = 256,
	PHP_CBOR_TAG_STRING_REF = 25,
};

#define PHP_CBOR_TAG_STRING_REF_ON_NS  2
